apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-load-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-load-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 2


